javac tage\*.java
javac tage\input\*.java
javac tage\input\action\*.java
javac tage\networking\*.java
javac tage\networking\client\*.java
javac tage\networking\server\*.java
javac tage\nodeControllers\*.java
javac tage\shapes\*.java
javac tage\objectRenderers\*.java
javac tage\physics\*.java
javac tage\physics\JBullet\*.java
javac tage\rml\*.java
javac tage\ai\behaviortrees\*.java
javac tage\audio\*.java
javac tage\audio\joal\*.java